blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blogs.urls')),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),

    # Custom accounts routes (e.g., register)
    path("accounts/", include("accounts.urls")),
    # Django's built-in auth (login/logout/password reset, etc.)
    path("accounts/", include("django.contrib.auth.urls")),

    path("learning_logs/", include("learning_logs.urls")),
    path("pizzas/", include("pizzas.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path("blogs/", include("blog.urls")),
]

pizzas/urls.py
"""Defines URL patterns for pizzas."""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page showing all pizzas.
    path('pizzas/', views.pizzas, name='pizzas'),
    # Page showing an individual pizza.
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
]

pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

class Pizza(models.Model):
    """A pizza that can be ordered from the pizzeria."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name


class Topping(models.Model):
    """A topping that can be added to a pizza."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a simple string representing the entry."""
        return self.name

pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """The home page for Pizzeria."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Page showing all pizzas that are available."""
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()

    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

pizzas/templates/pizzas/base.html
{% extends "base.html" %}

{% block app_nav %}
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>
{% endblock %}

{% block content %}{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
    <p>Welcome to the Pizzeria! We hope you'll find a pizza that is skibidi-licious! :)</p>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizza: {{pizza.name}} </p>

<p>Toppings:</p>
<ul>
    {% for topping in toppings %}
      <li>{{ topping.name }}</li>
    {% empty%}
      <li>There are no toppings on this pizza.</li>
    {% endfor %}
</ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzas</p>
<ul>
    {% for pizza in pizzas %}
      <li>
          <a href="{% url 'pizzas:pizza' pizza.id %}">
             {{ pizza.name }}</a>
      </li>
    {% empty %}
      <li>We don't currently have any pizzas available.</li>
    {% endfor %}
</ul>

{% endblock content %}